export const fetchSessionMe = async () => {
  return {
    user_id: "sec_ops_01",
    role: "Analyst",
    name: "Alex V.",
  };
};

export const fetchDashboardData = async () => {
  return {
    session_user: "user_45",
    generated_at: new Date().toISOString(),
    alerts: [
      { id: "ALRT-3201", severity: "high", message: "Suspicious credential pattern" },
      { id: "ALRT-3202", severity: "medium", message: "Multiple failed logins from 2 IPs" },
    ],
    assets: [
      { asset_id: "srv-01", name: "Finance API Node", status: "degraded" },
      { asset_id: "srv-02", name: "User Auth Node", status: "secure" }
    ],
    note: "Synthetic response generated by PhantomShield mock API"
  };
};

export const fetchForensicsSummary = async () => {
  return {
    total_sessions: 142,
    active_decoys: 12,
    high_risk_sessions: 4
  };
};

export const fetchSessionsFeed = async () => {
  return [
    { session_id: "sess_123", user_id: "user_45", risk_score: 0.88, routing_state: "DECOY", last_activity: "2026-04-02T12:40:00Z", status: "active" },
    { session_id: "sess_124", user_id: "user_12", risk_score: 0.12, routing_state: "REAL", last_activity: "2026-04-02T12:35:00Z", status: "active" },
    { session_id: "sess_125", user_id: "user_99", risk_score: 0.95, routing_state: "DECOY", last_activity: "2026-04-02T12:41:00Z", status: "active" },
    { session_id: "sess_126", user_id: "user_02", risk_score: 0.05, routing_state: "REAL", last_activity: "2026-04-02T12:20:00Z", status: "closed" }
  ];
};

export const fetchDecoyInteractions = async () => {
  return [
    { session_id: "sess_123", action: "view_report", target: "quarterly_finance", confidence: "medium", timestamp: "2026-04-02T12:41:10Z" },
    { session_id: "sess_125", action: "download", target: "ssh_keys.zip (fake)", confidence: "high", timestamp: "2026-04-02T12:42:05Z" },
    { session_id: "sess_123", action: "db_query", target: "users_table", confidence: "high", timestamp: "2026-04-02T12:43:00Z" }
  ];
};
