from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, Depends, status
from pydantic import BaseModel, Field

from app.middleware.auth import get_current_user

router = APIRouter(prefix="/decoy", tags=["decoy"])


class DecoyActionRequest(BaseModel):
    """Payload captured from interactions inside decoy endpoints."""

    action: str = Field(min_length=1, max_length=100)
    target: str | None = Field(default=None, max_length=255)
    metadata: dict[str, Any] = Field(default_factory=dict)


class DecoyDashboardResponse(BaseModel):
    """Fake dashboard returned to sessions routed to decoy."""

    session_user: str
    generated_at: datetime
    alerts: list[dict[str, Any]]
    assets: list[dict[str, Any]]
    note: str


@router.get("/health")
def health_check() -> dict[str, str]:
    """Liveness probe for decoy API."""

    return {"status": "ok", "service": "decoy"}


@router.get("/dashboard", response_model=DecoyDashboardResponse)
def get_decoy_dashboard(user: str = Depends(get_current_user)) -> DecoyDashboardResponse:
    """Return fake dashboard data for suspicious sessions."""

    return DecoyDashboardResponse(
        session_user=user,
        generated_at=datetime.now(timezone.utc),
        alerts=[
            {"id": "ALRT-3201", "severity": "high", "message": "Credential spray attempt"},
            {"id": "ALRT-3209", "severity": "medium", "message": "Abnormal geolocation shift"},
        ],
        assets=[
            {"asset_id": "srv-fin-12", "name": "Finance API Node", "status": "degraded"},
            {"asset_id": "db-ledger-03", "name": "Ledger Replica", "status": "investigating"},
        ],
        note="Synthetic decoy response generated by PhantomShield.",
    )


@router.post("/interaction", status_code=status.HTTP_202_ACCEPTED)
def capture_decoy_interaction(
    payload: DecoyActionRequest,
    user: str = Depends(get_current_user),
) -> dict[str, Any]:
    """Capture interaction metadata for future forensic logging."""

    return {
        "accepted": True,
        "session_user": user,
        "recorded_action": payload.action,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }